### ISSUE TITLE
Consider some way to configure unix socket path

### ISSUE THREAD

**Issue by wolfeidau** [google/gops#10]
Just reviewing the code and would love a way to move that socket out of `/tmp` to say `/var/run` for services. Reason I mention it is the `PrivateTmp` feature provided by systemd.

Maybe an environment variable would be the simplest way to override?

Cheers

**Comment by rakyll** [comment]
I want to move off of the unix socket and want to listen on a TCP socket instead. I am planning to listen on a random port and keep the port process is listening under $HOME/.gops/<pid>.addr. This will also enable the windows support.

**Comment by wolfeidau** [comment]
I think both would be great given access to the unix socket can be controlled using filesystem permissions. 

Discovery with the random high port is an interesting challenge, given a system could be running many of these services. Not sure i have seen this done well yet to be honest, always ends up being configured on a per process basis, or coordinated using a central service.

Really looking forward to trying this out.

**Comment by ahmetalpbalkan** [comment]
Agreed, /var/run/*.sock would be more preferable.

Windows support possibly can be enabled with named pipes OS construct as well. I'm not familiar with that as much, but it should be doable. To be more on the modern side of the things, perhaps gops can be an HTTP endpoint that registers its handlers, just like `import _ "net/http/pprof"` does and starting agent would be as simple as importing a package and a `http.ListenAndServe(addr, nil)`?

**Comment by rakyll** [comment]
We are switching to a TCP socket, see https://github.com/google/gops/pull/11.

**Comment by shurcooL** [comment]
> I want to move off of the unix socket and want to listen on a TCP socket instead.

I'm asking because I don't know and would like to learn, what's the reason for you wanting to do that?

You mentioned this would "also" enable windows support, so it sounds like that's not the primary reason. Are there other reasons?
