### ISSUE TITLE
gops doesn't list processes built with go1.14

### ISSUE THREAD

**Issue by donaldthai** [google/gops#100]
Hello,

I recently upgraded to `go1.14` and `gops` isn't listing my processes now. Any timeline to support the latest go version?

**Comment by Clivern** [comment]
Hi @donaldthai 

May be you need to reinstall gops? because i see it works with go1.14

```
➜  $ go version
go version go1.14 darwin/amd64
➜  $ gops
52652 47075 gops  go1.14 /Users/Ahmed/go/bin/gops
```

**Comment by donaldthai** [comment]
@Clivern 

DOH! You're right, I just needed to update to the latest version of gops! Thanks!
