### ISSUE TITLE
gops stopped listing my running go programs

### ISSUE THREAD

**Issue by prithsharma** [google/gops#102]
A few days ago, `gops` stopped listing my running go program (found this when I couldn't attach to my program for debugging in GoLand)

Any ideas on how to debug this?

**Comment by rakyll** [comment]
Is it possible for you to see if https://godoc.org/rsc.io/goversion is working with your binary?

**Comment by prithsharma** [comment]
Right, `goversion` doesn't list my binary either. I can confirm that some other binaries lying in my directory from before are being listed with `goversion` but the binary in question (which I recently generated) is not. May be something changed on my system? what should I check?

**Comment by tklauser** [comment]
@prithsharma could you check whether you still see the issue with the latest `gops` version? If you do, could you check with which Go version your binary was compiled using both `goversion <binary>` (using the latest version of `goversion`) and `go version <binary>`?

**Comment by lblackstone** [comment]
I ran into this same issue today. Here's the output from both `go version` and `goversion`:

```
$ go version ~/go/bin/pulumi-resource-kubernetes
/Users/levi/go/bin/pulumi-resource-kubernetes: go1.15.7

$ goversion ~/go/bin/pulumi-resource-kubernetes
/Users/levi/go/bin/pulumi-resource-kubernetes: implausible string size 13678730008574592512 for runtime.buildVersion
```

**Comment by lblackstone** [comment]
This open issue with `goversion` looks like the culprit: https://github.com/rsc/goversion/issues/12

**Comment by tklauser** [comment]
I think #166 should fix this issues, at least when building `gops` using Go 1.18.

@prithsharma @lblackstone could you please check whether `gops` built from latest `master` branch using Go 1.18 works as expected for you?

**Comment by lblackstone** [comment]
> @lblackstone could you please check whether `gops` built from latest `master` branch using Go 1.18 works as expected for you?

Yes, this appears to be working as expected now. Thanks!

**Comment by tklauser** [comment]
@lblackstone Thanks for confirming!
