### ISSUE TITLE
Implausible string size error when reading Mach-O files with symbolic debugging entry

### ISSUE THREAD

**Issue by niboge** [google/gops#117]
https://github.com/rsc/goversion/issues/12

wish change rsc/goversion commitid to 5f05606419ef23cba7b3d6e4bca83e43df9825ad  2020.5

**Comment by niboge** [comment]
gops can not see the go progress with special mac debug symbol

**Comment by tklauser** [comment]
This should be fixed by #166 in v0.3.23.
