### ISSUE TITLE
(newest) gops crashed in go1.15

### ISSUE THREAD

**Issue by ifory** [google/gops#122]
for easy to crash, build the hello example as windows exe program.
launch the exe program ten times.
then just use gops in console, it is happen.

**Comment by yarcat** [comment]
Seems to be related to #123

**Comment by yarcat** [comment]
@ifory Could you please try to latest version. Imho the problem should be gone.
https://github.com/google/gops/releases/tag/v0.3.12

**Comment by rakyll** [comment]
This should be fixed, can we get a confirmation?
