### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Kaiser925** [google/gops#147]
use ``` go get -u github.com/google/gops``` install gops failed, got

```shell
go get: github.com/StackExchange/wmi@v0.0.0-20190523213315-cbe66965904d updating to
	github.com/StackExchange/wmi@v0.0.0-20210708210415-b284ef6ab838: parsing go.mod:
	module declares its path as: wmi
	        but was required as: github.com/StackExchange/wm
```

**Comment by tklauser** [comment]
I think the installation instructions in the `README` are slightly incorrect. We should either use `go install github.com/google/gops` or `go get github.com/google/gops` (without `-u`) to install the binary. @Kaiser925 could you check whether one of the commands works for you?

I'll send a PR fixing the `README`.

**Comment by Kaiser925** [comment]
Thank you for your reply, @tklauser . Command  ```go get github.com/google/gops`` worked for me.
