### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by thomasmodeneis** [google/gops#16]
Hi,

I'm not clear on how this package is actually working, when I try to follow the steps on the readme.md I'm running into: `no such file or directory`

This is the complete logs:
```
test@test:~# /opt/gocode/bin/gops
2153	        grafana-server	(/usr/sbin/grafana-server)
4496	        influxd	(/usr/bin/influxd)
4506 	gops	(/opt/gocode/bin/gops)

90 processes left undetermined
test@test:~# /opt/gocode/bin/gops stack -p=4496
open /test/.config/gops/4496: no such file or directory
```

Any ideas ?

Cheers.

**Comment by ale64bit** [comment]
The process `4496` is not running the agent. When a process is running the agent, it's marked with a `*`. For example:
```
2153	        grafana-server	(/usr/sbin/grafana-server)
4496*	        influxd	(/usr/bin/influxd)
4506 	gops	(/opt/gocode/bin/gops)
```
In that case you can attach to it. See the README example for how to start the agent in your own projects.

**Comment by thomasmodeneis** [comment]
Oh right, I see now.

So that would only work to inspect projects I'm currently able to modify the contents, introduce the required libs, start it and then I will be able to debug, correct ?
Now I fully understand the sentence on the readme `For processes that starts the diagnostics agent, gops can report additional information`.

Thanks.
