### ISSUE TITLE
gops depends on the now retracted github.com/shirou/gopsutil v3.22.11

### ISSUE THREAD

**Issue by siebenmann** [google/gops#191]
Gops depends on v3.22.11 of gopsutil after commit 9430031e1a271b091eb514149192e5f1bd3f6b61 from pull #189. However, a tag for this version is no longer present in https://github.com/shirou/gopsutil and the repository's go.mod currently marks this version as retracted (which was added in shirou/gopsutil@032376bae404b92839a6d5d65d15fa2bbc6d4736, and see also shirou/gopsutil#1386). This appears to be potential bad timing; the dependabot pull may have been opened in a narrow window between the tag being published and the tag being removed and retracted.

(Some builds of gops will continue working because the default public Go module proxy has cached v3.22.11.)

**Comment by tklauser** [comment]
Thanks for the report @siebenmann. This should be fixed by #192.
