### ISSUE TITLE
Error with go get.

### ISSUE THREAD

**Issue by varun06** [google/gops#2]
### Error - 

#github.com/google/gops/internal/objfile
go/src/github.com/google/gops/internal/objfile/goobj.go:119: undefined: gosym.PCValue
go/src/github.com/google/gops/internal/objfile/goobj.go:126: undefined: gosym.PCValue

### `go env`
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="<my go path>"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2w/fcrm_b9n28d1knhgqmvl24j8bjsl2j/T/go-build300906419=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by tmdvs** [comment]
I'm also experiencing the same issue on macOS. Can't find any reference to PCValue on the gosym docs page so assuming its referencing a different version of gosym?

**Comment by siadat** [comment]
Which version of go are you using? Please post the output of `go version`.

My guess is that you are using a released version of Go. PCValue is a relatively new and will be added to the gosym package in Go1.8 according to golang/go#13862.

**Comment by varun06** [comment]
I am on `go1.7.3`

**Comment by peterhellberg** [comment]
Yes, this fails on `go get` using version 1.7.3 under macOS 10.11.6 (El Capitan)

**Comment by rakyll** [comment]
Disabling gosym for now, we don't have to disassemble .o files.
