### ISSUE TITLE
Report Go version without the agent

### ISSUE THREAD

**Issue by rakyll** [google/gops#22]
See Damian's script to dissemble and extract the version information at https://gist.github.com/dgryski/99ac147faf2891c9816d3f4f925c4e6b.

**Comment by rsc** [comment]
Fixed?

**Comment by odeke-em** [comment]
Perhaps what @rsc did in https://github.com/rsc/goversion can be done here too? Or we can transform his work a package and then import it in this package, that's importable and useable here.

**Comment by rakyll** [comment]
Thanks @rsc!

@odeke-em, it is already done. I converted goversion into a library at https://github.com/google/gops/tree/master/internal/goversion. We need to remove the version subcommand. Do you want to send a change?
