### ISSUE TITLE
Write cpu profile to socket

### ISSUE THREAD

**Issue by iand** [google/gops#26]
The cpu profile is taken by the agent but never written to the socket. Happy to submit a PR for the change if needed.

**Comment by rakyll** [comment]
Please feel free to open a PR, otherwise I will take a look.

**Comment by rakyll** [comment]
The profile is written to the socket, are you sure that you are running a program that does anything at all? If you run the example program, since it keeps waiting on the sleep, the profile gathered is often empty. Though with an actual CPU-intense program, I can see the samples.

**Comment by iand** [comment]
My mistake. Sorry for the noise.
