### ISSUE TITLE
stat the pid file to report agent running processes

### ISSUE THREAD

**Issue by rakyll** [google/gops#27]
Currently, we are looking for the agent symbol's existence to report if a process is running the agent. This assertion doesn't help if the agent is closed. We should instead stat the gops pid file for the process to see if the agent is actively listening.

**Comment by qzaidi** [comment]
+1 to this. Using the symbols cause another problem for us, because our packaging (debian) normally strips the binaries before deploying to production. So even if we use the agent, we have to use unstripped binaries.
