### ISSUE TITLE
Report process info

### ISSUE THREAD

**Issue by rakyll** [google/gops#58]
gops can report more process info (e.g. https://godoc.org/github.com/shirou/gopsutil/process) for a PID. The only downside is that this command will be asymmetrical because we cannot provide the same functionality for the processes working remotely. 

```
$ gops <pid>
Create time: XXX
Number of threads: 4
Number of context switches: X
Number of file descriptors: X
Number of open files: X

Connections
...
```

@odeke-em, what do you think?

**Comment by odeke-em** [comment]
That'd be amazing and quite useful for folks running stuff on the cloud. The number of open files most especially. Thanks for filing this issue.

**Comment by rakyll** [comment]
We can import gopsutil into the agent and make it work on the remote processes as well. I am taking my words back that it will be an asymmetrical feature.

Do you want me to assign this to myself and send out a change?

**Comment by odeke-em** [comment]
Please do so.
