### ISSUE TITLE
What's the gops's roadmap ?

### ISSUE THREAD

**Issue by zuoRambo** [google/gops#62]
In `java` domain, they have `JMX` and `jmxtrans`, so they could build an platform to monitoring the java application clusters.
With the help of `grafana`、`kibana`、`ganglia`、`prometheus` or `zabbix`、`openfalcon`, they could config one monitoring solution which has displaying and alerting feature.

So, what can our `gops` do ?
Now, we could report real-time runtime info by agent mode. 
But, the representation is not enough and not intuitive. 
Otherwise, we want collect real-time info and record history data. 
I think we could report mertics to time-series DB(as InfluxDB). 
We could support runtime monitoring solution for `golang ecology`.

**Comment by zuoRambo** [comment]
https://github.com/bmhatfield/go-runtime-metrics
https://github.com/tevjef/go-runtime-metrics

**Comment by rakyll** [comment]
Sorry, currently we are not planning to extend this tool in a way it depends on external services. gops is currently a tiny tool that does one job and does it well. 

@odeke-em had some ideas for auto-discovery of Go processes in a cluster and provide more compelling features but I don't think it has to be gops but can be implemented as a separate tool.

**Comment by zuoRambo** [comment]
@rakyll Thanks for answer～
