### ISSUE TITLE
where is the cmds defined

### ISSUE THREAD

**Issue by guojun1992** [google/gops#7]
func main() {
	if len(os.Args) < 2 {
		processes()
		return
	}

	cmd := os.Args[1]
	if cmd == "help" {
		usage("")
	}
	fn, ok := cmds[cmd]
	if !ok {
		usage("unknown subcommand")
	}

**Comment by siadat** [comment]
[cmd.go#L15](https://github.com/google/gops/blob/9423f02414bd894a9b5fe49dbcb330dbee114c55/cmd.go#L15)
