### ISSUE TITLE
Cannot run stack command 

### ISSUE THREAD

**Issue by ZouRui89** [google/gops#73]
I kept getting 'connection refused' info when trying to run 'gops stack  (<pid>|<addr>)' command.

[root@izj6c44nzox6sb97nzgmhyz ~]# gops
13136 13128 containerd  unknown Go version /usr/local/bin/containerd
13650 13235 gops        go1.9.1            /usr/local/go/bin/gops
13128 7610  pouchd      go1.9.1            /usr/local/bin/pouchd
[root@izj6c44nzox6sb97nzgmhyz ~]# gops stack 13128
couldn't get port by PID: dial tcp 127.0.0.1:0: getsockopt: connection refused

**Comment by odeke-em** [comment]
Sorry for the late reply @ZouRui89, we've been quite swamped with day work. However, welcome to gops! I see you closed the issue, were you able to resolve it okay?

**Comment by ZouRui89** [comment]
Hi, I was using gops to test pouch, a container engine we are working on, and kept getting this problem  the other day. Then I realized that it is the setting in pouch that stopped gops unless it is debug mode, in which case I closed the issue.
Thx for your replay. I really appreciate it. :)

**Comment by odeke-em** [comment]
Ahh, I see. Great, thank you for the post mortem post and thank you for using gops!
