### ISSUE TITLE
Support runtime.SetGCPercent

### ISSUE THREAD

**Issue by rakyll** [google/gops#8]
Provide a command similar to runtime.SetGCPercent to change the GC percentage dynamically during runtime.

```
$ gops setgc -p=<pid> 60 # Sets GC to 60%
$ gops setgc -p=<pid> -1 # Disables GC
```

**Comment by danielfireman** [comment]
Hi @rakyll, good morning.

I noticed you're assigned to this one, but as the issue was opened at Nov 14, 2016, I thought it was ok to ask: can I try to tackle this issue?

**Comment by rakyll** [comment]
Surely, go for it.
