### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by danp** [google/gops#96]
Hi there,

Would it be possible to cut a new release? It would be especially nice to get #87 in a released version.

Thanks!

**Comment by rakyll** [comment]
https://github.com/google/gops/releases/tag/v0.3.7 is released.

**Comment by danp** [comment]
Thanks!

Double checking: should that have been 0.3.8 as of current master? I think 0.3.7 already existed, for 59c8be2eaddf480111508bccd11505912168d23a, which https://github.com/google/gops/releases/tag/v0.3.7 still points to.
